name: Create Release

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Get Current Changes
      id: changes
      run: |
        export VERSION=$(cat package.json | jq -r '.version') && echo "$(node bin/index.js cat -r $VERSION)" > releaseBody.md
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: releaseBody.md
        token: ${{ secrets.WORKFLOW_TOKEN }}
